apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-example-dev
resources:
  - deployment.yaml
images:
  - name: harbor.osdc.local/apps/rust-axum-api
    newTag: replace-me
