Include /etc/coraza/coraza.conf-recommended
Include /etc/coraza/owasp-crs/crs-setup.conf
Include /etc/coraza/owasp-crs/rules/*.conf

SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecAuditEngine RelevantOnly
SecAuditLog /var/log/coraza/audit.log
